apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  namespace: default
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  PRODUCT_DB: productdb
  AUTH_SERVICE: auth-service:5000
  PRODUCT_SERVICE: product-service:5000

  # ORDER_DB: orderdb
