apiVersion: v1
kind: Secret
metadata:
  name: product-secrets
  namespace: default
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "123456789"
  MYSQL_USER: "productuser"
  MYSQL_PASSWORD: "productpassword"
  JWT_SECRET: "SuperSecretAPI"
