apiVersion: v1
kind: Service
metadata:
  name: product-db-service
  namespace: default
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: default
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
