apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: default
type: Opaque
stringData:
  JWT_SECRET: "SuperSecretAPI"
  CHARGILY_API_KEY: test_pk_OWKUvx53qLLApOSha4uZV7RBWPAsKCVVIvGnZ3B8
  CHARGILY_API_SECRET: test_sk_oEQkA56exTVv2Ht4hapzAIUD8m1YtosKHJjiz1I9
  RABBITMQ_USER: admin
  RABBITMQ_PASSWORD: admin