apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: default
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  USER_DB: users_db
  JWT_EXPIRY: 24h
  # PRODUCT_DB: productdb
  # ORDER_DB: orderdb
