apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: default
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: MTIzNDU2Nzg5
  MYSQL_USER: YXV0aHVzZXI=
  MYSQL_PASSWORD: YXV0aHBhc3N3b3Jk
  JWT_SECRET: SuperSecretAPI
