apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        envFrom:
          - configMapRef:
              name: auth-config
          - secretRef:
              name: auth-secrets
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: MYSQL_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: auth-config
                key: USER_DB
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: data-pvc-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z user-db-service 3306; do echo "waiting for mysql..."; sleep 5; done;']
      
      containers:
      - name: auth-service
        image: abdelkader97/auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: auth-config
          - secretRef:
              name: auth-secrets
        env:
          - name: DB_HOST
            value: user-db-service
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: MYSQL_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: MYSQL_PASSWORD
          - name: DB_NAME 
            valueFrom:
              configMapKeyRef:
                name: auth-config
                key: USER_DB
          - name: JWT_SECRET 
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: JWT_SECRET
          - name: JWT_EXPIRY 
            valueFrom:
              configMapKeyRef:
                name: auth-config
                key: JWT_EXPIRY
          - name: PORT
            value: "5000"
