apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
  namespace: default
type: Opaque
stringData:
  TWILIO_ACCOUNT_SID: AC79b418620fcb2b939ad428c63a7b578a
  TWILIO_AUTH_TOKEN: b89b6bcd8eb35313277f20f4a03b3fb2
  EMAIL_USER: bouchouichaaek97@gmail.com
  EMAIL_PASS: "nqvz shyq dxjs vmaf"
  RABBITMQ_USER: admin
  RABBITMQ_PASSWORD: admin
