apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        envFrom:
          - configMapRef:
              name: order-config
          - secretRef:
              name: order-secrets
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: order-secrets
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: order-secrets
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: order-secrets
                key: MYSQL_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: order-config
                key: ORDER_DB


        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: data-pvc-order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z order-db-service 3306; do echo "waiting for order-db..."; sleep 5; done;']

      containers:
      - name: order-service
        image: abdelkader97/order-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: order-config
          - secretRef:
              name: order-secrets
        env:
          - name: DB_HOST
            value: order-db-service
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: order-secrets
                key: MYSQL_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: order-secrets
                key: MYSQL_PASSWORD
          - name: DB_NAME 
            valueFrom:
              configMapKeyRef:
                name: order-config
                key: ORDER_DB
          - name: JWT_SECRET 
            valueFrom:
              secretKeyRef:
                name: order-secrets
                key: JWT_SECRET
          - name: JWT_EXPIRY 
            valueFrom:
              configMapKeyRef:
                name: order-config
                key: JWT_EXPIRY
          - name: PORT
            value: "5000"
          - name: AUTH_SERVICE
            valueFrom:
              configMapKeyRef:
                name: order-config
                key: AUTH_SERVICE
          - name: PRODUCT_SERVICE
            valueFrom:
              configMapKeyRef:
                name: order-config
                key: PRODUCT_SERVICE
          - name: ORDER_SERVICE
            valueFrom:
              configMapKeyRef:
                name: order-config
                key: ORDER_SERVICE
